language: java

jdk:
  - openjdk18

before_install:
  - sudo apt install default-jdk
  - sudo apt-get update -qq
  - sudo apt install default-jre
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V


after_success:
  - .buildscript/deploy_snapshot.sh
